#!/bin/bash

mkdir -p /tmp/rom # Where to sync source
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init -q --no-repo-verify --depth=1 -u https://github.com/P-404/platform_manifest -b rippa -g default,-device,-mips,-darwin,-notdefault

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 30 || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 8

# Device Sources
git clone https://github.com/massterpiece/tissot_caf.git -b eleven device/xiaomi/tissot
git clone https://github.com/massterpiece/msm8953-common_caf.git -b eleven device/xiaomi/msm8953-common
git clone https://github.com/neonmicky/android_kernel_xiaomi_msm8953.git -b eleven kernel/xiaomi/msm8953 --depth=1
git clone https://gitlab.com/MASTERGUY/proprietary_vendor_xiaomi.git -b eleven vendor/xiaomi --depth=1
rm -rf hardware/qcom/media hardware/qcom/display vendor/qcom/opensource/audio-hal/primary-hal hardware/qcom/bootctrl vendor/qcom/opensource/commonsys-intf/display
git clone https://github.com/Unknownbitch07/R-Hals.git -b display-r hardware/qcom/display
git clone https://github.com/Unknownbitch07/R-Hals.git -b media-r hardware/qcom/media
git clone https://github.com/LineageOS/android_hardware_qcom_audio.git -b lineage-18.1-caf-msm8996 vendor/qcom/opensource/audio-hal/primary-hal
git clone https://github.com/LineageOS/android_hardware_qcom_bootctrl.git -b lineage-18.1-caf hardware/qcom/bootctrl

